// <auto-generated />
using System;
using CDNMiddleware.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDNMiddleware.DataAccess.Migrations
{
    [DbContext(typeof(CDNMiddlewareDbContext))]
    partial class CDNMiddlewareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CDNMiddleware.DataAccess.Models.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Hobby")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("hobby");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("mail");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Skillsets")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("skillsets");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("username");

                    b.HasKey("ID");

                    b.HasIndex("Mail");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("Username");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
